export const word = [
  // فواكه
  { category: "فواكه", wordGuess: "موز", hint: "اصفر اللون وغني بالطاقة" },
  { category: "فواكه", wordGuess: "تفاح", hint: "مقرمش ولذيذ ومفيد للقلب" },
  { category: "فواكه", wordGuess: "عنب", hint: "صغير الحجم ينمو في عناقيد" },
  { category: "فواكه", wordGuess: "تين", hint: "لين وحلو الطعم ومغذي" },
  { category: "فواكه", wordGuess: "خوخ", hint: "ناعم وعطري ولذيذ الطعم" },
  {
    category: "فواكه",
    wordGuess: "رمان",
    hint: "حبوب حمراء مليئة بالفيتامينات",
  },
  { category: "فواكه", wordGuess: "ليمون", hint: "حامض الطعم غني بالفيتامين" },
  { category: "فواكه", wordGuess: "مانجو", hint: "استوائي حلو ولذيذ المذاق" },
  { category: "فواكه", wordGuess: "اناناس", hint: "حامض وحلو ويستعمل عصير" },
  { category: "فواكه", wordGuess: "كيوي", hint: "صغير أخضر مليء بالفيتامينات" },
  { category: "فواكه", wordGuess: "برتقال", hint: "عصيري ولونه برتقالي غني" },
  { category: "فواكه", wordGuess: "جوافه", hint: "غني بالفيتامين ومفيد للصحة" },

  // خضار
  { category: "خضار", wordGuess: "بصل", hint: "يسبب الدموع عند التقطيع" },
  { category: "خضار", wordGuess: "جزر", hint: "مفيد للنظر والصحة العامة" },
  { category: "خضار", wordGuess: "فجل", hint: "طعمه حار ولاذع قليلا" },
  { category: "خضار", wordGuess: "خس", hint: "يؤكل طازج في السلطات" },
  { category: "خضار", wordGuess: "بطاطس", hint: "تطبخ بعدة طرق مختلفة" },
  { category: "خضار", wordGuess: "طماطم", hint: "حمراء اللون وتستخدم بالطبخ" },
  { category: "خضار", wordGuess: "خيار", hint: "مفيد للبشرة" },
  { category: "خضار", wordGuess: "فلفل", hint: "حار أو حلو حسب النوع" },
  { category: "خضار", wordGuess: "باذنجان", hint: "يطبخ مشوي او مقلي كثيرا" },
  { category: "خضار", wordGuess: "ذره", hint: "حبات صغيرة صفراء اللون" },

  // طعام
  { category: "طعام", wordGuess: "خبز", hint: "يُصنع من القمح الطازج" },
  { category: "طعام", wordGuess: "ارز", hint: "حبوب بيضاء تستخدم بالطبخ" },
  { category: "طعام", wordGuess: "حساء", hint: "طبق ساخن يشرب عادة" },
  { category: "طعام", wordGuess: "عسل", hint: "طعام حلو ينتجه النحل" },
  { category: "طعام", wordGuess: "جبن", hint: "يصنع من حليب البقر" },
  { category: "طعام", wordGuess: "كباب", hint: "لحم مشوي على الفحم عادة" },
  { category: "طعام", wordGuess: "حمص", hint: "طبق مشهور من الشرق الاوسط" },
  { category: "طعام", wordGuess: "بيتزا", hint: "عجينة مغطاة بالجبن والصلصة" },
  { category: "طعام", wordGuess: "برجر", hint: "لحم مفروم داخل خبز دائري" },
  { category: "طعام", wordGuess: "سوشي", hint: "أرز مع سمك نيء" },
  { category: "طعام", wordGuess: "فلافل", hint: "كرات مقلية من الحمص" },
  { category: "طعام", wordGuess: "مندي", hint: "رز ولحم مطهو بطريقة خاصة" },

  // حيوان
  { category: "حيوان", wordGuess: "اسد", hint: "ملك الغاب" },
  { category: "حيوان", wordGuess: "نمر", hint: "سريع وخطر" },
  { category: "حيوان", wordGuess: "فيل", hint: "ضخم جدا" },
  { category: "حيوان", wordGuess: "ذئب", hint: "يعيش في البر" },
  { category: "حيوان", wordGuess: "حصان", hint: "سريع وقوي" },
  { category: "حيوان", wordGuess: "قرد", hint: "يحب موز" },
  { category: "حيوان", wordGuess: "دب", hint: "قوي وضخم" },
  { category: "حيوان", wordGuess: "جمل", hint: "سفينه الصحراء" },

  // وظيفة
  { category: "وظيفة", wordGuess: "طبيب", hint: "يعالج المرضى ويهتم بصحتهم" },
  { category: "وظيفة", wordGuess: "معلم", hint: "يشرح الدروس للطلاب يوميا" },
  { category: "وظيفة", wordGuess: "نجار", hint: "يصنع الاثاث من الخشب" },
  {
    category: "وظيفة",
    wordGuess: "حداد",
    hint: "يعمل في تشكيل الحديد والمعادن",
  },
  { category: "وظيفة", wordGuess: "شرطي", hint: "يحافظ على النظام والأمن" },
  {
    category: "وظيفة",
    wordGuess: "مهندس",
    hint: "يصمم المباني والجسور المختلفة",
  },
  {
    category: "وظيفة",
    wordGuess: "ممرض",
    hint: "يرعى المرضى داخل المستشفى يوميا",
  },
  {
    category: "وظيفة",
    wordGuess: "خباز",
    hint: "يخبز الخبز والمعجنات الطازجة",
  },
  { category: "وظيفة", wordGuess: "حلاق", hint: "يقص الشعر ويهتم بالمظهر" },
  { category: "وظيفة", wordGuess: "صيدلي", hint: "يبيع الادوية ويوجه المرضى" },
  {
    category: "وظيفة",
    wordGuess: "رسام",
    hint: "يرسم لوحات فنية جميلة وملونة",
  },

  // جماد
  { category: "جماد", wordGuess: "قلم", hint: "يستخدم في التدوين و الرسم" },
  { category: "جماد", wordGuess: "كتاب", hint: "مصدر للمعرفة و زيادة الثقافة" },
  { category: "جماد", wordGuess: "هاتف", hint: "جهاز للتواصل بين الناس يوميا" },
  {
    category: "جماد",
    wordGuess: "مفتاح",
    hint: "اداة معدنية لفتح الابواب المختلفة",
  },
  {
    category: "جماد",
    wordGuess: "حاسب",
    hint: "جهاز الكتروني لمعالجة البيانات بسرعة",
  },
  {
    category: "جماد",
    wordGuess: "ساعه",
    hint: "تستخدم لمعرفة الوقت خلال اليوم",
  },
  {
    category: "جماد",
    wordGuess: "كرسي",
    hint: "يستخدم للجلوس في المنازل والمكاتب",
  },
  {
    category: "جماد",
    wordGuess: "طاوله",
    hint: "سطح مستو يستخدم لوضع الاشياء",
  },
  { category: "جماد", wordGuess: "مصباح", hint: "جهاز يضيء المكان عند الظلام" },
  {
    category: "جماد",
    wordGuess: "حقيبه",
    hint: "تستخدم لحمل الاغراض الشخصية يوميا",
  },
  {
    category: "جماد",
    wordGuess: "باب",
    hint: "جزء يستخدم للدخول والخروج للغرف",
  },
  {
    category: "جماد",
    wordGuess: "نافذه",
    hint: "فتحة تسمح بدخول الضوء والهواء",
  },

  // دول
  { category: "دول", wordGuess: "مصر", hint: "مشهورة بالاهرامات" },
  { category: "دول", wordGuess: "الإمارات", hint: "اطول برج بالعالم" },
  { category: "دول", wordGuess: "السعوديه", hint: "فيها مكة المكرمة" },
  { category: "دول", wordGuess: "المغرب", hint: "فازت بكأس العرب 2025" },
  { category: "دول", wordGuess: "الجزائر", hint: "اكبر دولة افريقيا" },
  { category: "دول", wordGuess: "تونس", hint: "تونس الخضراء" },
  { category: "دول", wordGuess: "العراق", hint: "بلاد الرافدين" },
  { category: "دول", wordGuess: "سوريا", hint: "عاصمتها دمشق" },
  { category: "دول", wordGuess: "الأردن", hint: "مدينة البتراء الوردية" },
  { category: "دول", wordGuess: "فلسطين", hint: "القدس الشريف" },
  { category: "دول", wordGuess: "تركيا", hint: "بين قارتين" },
  { category: "دول", wordGuess: "فرنسا", hint: "مشهورة ببرج ايفل" },
  { category: "دول", wordGuess: "ايطاليا", hint: "مشهورة بالبيتزا" },
  { category: "دول", wordGuess: "المانيا", hint: "صناعة السيارات" },
  { category: "دول", wordGuess: "الهند", hint: "مشهورة بالحناء" },
  { category: "دول", wordGuess: "الصين", hint: "السور العظيم" },
  { category: "دول", wordGuess: "اليابان", hint: "تكنولوجيا متقدمة" },
  { category: "دول", wordGuess: "البرازيل", hint: "مشهورة بكرة القدم النطيفة" },

  // رسوم متحركة
  { category: "رسوم متحركة", wordGuess: "كونان", hint: "محقق ذكي يحل الجرائم" },
  { category: "رسوم متحركة", wordGuess: "سيمبا", hint: "اسد يصبح ملك الغابة" },
  { category: "رسوم متحركة", wordGuess: "ماوكلي", hint: "طفل يعيش في الغابة" },
  {
    category: "رسوم متحركة",
    wordGuess: "دورايمون",
    hint: "قط روبوت من المستقبل",
  },
  {
    category: "رسوم متحركة",
    wordGuess: "بينوكيو",
    hint: "دمية تتحول الى انسان",
  },
  { category: "رسوم متحركة", wordGuess: "ريمي", hint: "فأر يحب الطبخ" },
  { category: "رسوم متحركة", wordGuess: "سونيك", hint: "قنفذ سريع جدا" },
  { category: "رسوم متحركة", wordGuess: "سالي", hint: "طفلة تعيش حياة صعبة" },
  { category: "رسوم متحركة", wordGuess: "ايروكا", hint: "فتاة تحب الغناء" },
  {
    category: "رسوم متحركة",
    wordGuess: "سندريلا",
    hint: "فتاة تفقد حذاءها الزجاجي",
  },
  {
    category: "رسوم متحركة",
    wordGuess: "همتارو",
    hint: "هامستر صغير يحب المغامرات",
  },
  {
    category: "رسوم متحركة",
    wordGuess: "القناص",
    hint: "مغامرات صيادين بقدرات خاصة",
  },
  {
    category: "رسوم متحركة",
    wordGuess: "الشبح",
    hint: "بطل كرة القدم و يلقب بالكابتن ماجد",
  },
]
