export const word = [
  {
    category: "Fruits",
    wordGuess: "BANANA",
    hint: "This yellow curved and take energy.",
  },
  {
    category: "Food",
    wordGuess: "PIZZA",
    hint: "Round, cheesy, and very popular.",
  },
  {
    category: "Movies",
    wordGuess: "INCEPTION",
    hint: "A dream within a dream.",
  },
  {
    category: "Jobs",
    wordGuess: "DOCTOR",
    hint: "Helps sick people get better.",
  },
  {
    category: "Sports",
    wordGuess: "FOOTBALL",
    hint: "Played with a ball and 11 players.",
  },
  {
    category: "Objects",
    wordGuess: "LAPTOP",
    hint: "Portable computer used for work.",
  },
  {
    category: "Countries",
    wordGuess: "ITALY",
    hint: "First country to make pizza.",
  },
  {
    category: "Animals",
    wordGuess: "ELEPHANT",
    hint: "The largest animal on land.",
  },
  {
    category: "Fruits",
    wordGuess: "ORANGE",
    hint: "Have many vitamin C if eat it.",
  },
  {
    category: "Jobs",
    wordGuess: "TEACHER",
    hint: "Explains lessons and educates students.",
  },
  {
    category: "Sports",
    wordGuess: "BASKETBALL",
    hint: "Players shoot a ball into a hoop.",
  },
  {
    category: "Objects",
    wordGuess: "TELEVISION",
    hint: "Used to watch shows and movies.",
  },
  {
    category: "Countries",
    wordGuess: "OMAN",
    hint: "A GCC with natural landscapes and mountains.",
  },
  {
    category: "Animals",
    wordGuess: "MONKEY",
    hint: "It's eat a lot of banana.",
  },
  {
    category: "Food",
    wordGuess: "BURGER",
    hint: "Bread, meat, and cheese stacked together.",
  },
  {
    category: "Movies",
    wordGuess: "AVATAR",
    hint: "Blue characters on a distant planet.",
  },
  { category: "Objects", wordGuess: "CAMERA", hint: "Used to take photos." },
  {
    category: "Jobs",
    wordGuess: "ENGINEER",
    hint: "Builds and designs structures and systems.",
  },
  {
    category: "Sports",
    wordGuess: "TENNIS",
    hint: "Played with a racket and small ball.",
  },
  {
    category: "Food",
    wordGuess: "SUSHI",
    hint: "Rice rolled with fish or vegetables.",
  },
  { category: "Fruits", wordGuess: "APPLE", hint: "Keeps the doctor away." },
  {
    category: "Countries",
    wordGuess: "JAPAN",
    hint: "Land of cherry blossoms.",
  },
  {
    category: "Animals",
    wordGuess: "LION",
    hint: "Known as the king of the jungle.",
  },
  {
    category: "Objects",
    wordGuess: "PHONE",
    hint: "Used for calling and texting.",
  },
  {
    category: "Jobs",
    wordGuess: "NURSE",
    hint: "Assists doctors and cares for patients.",
  },
  {
    category: "Sports",
    wordGuess: "SWIMMING",
    hint: "A sport practiced in water.",
  },
  { category: "Movies", wordGuess: "TITANIC", hint: "Famous ship love story." },
  { category: "Food", wordGuess: "PASTA", hint: "A popular Italian dish." },
  { category: "Animals", wordGuess: "TIGER", hint: "Striped orange wild cat." },
  { category: "Objects", wordGuess: "TABLE", hint: "Used to place items on." },
  {
    category: "Countries",
    wordGuess: "FRANCE",
    hint: "Known for the Eiffel Tower.",
  },
  {
    category: "Jobs",
    wordGuess: "LAWYER",
    hint: "Helps people in legal matters.",
  },
  {
    category: "Sports",
    wordGuess: "BOXING",
    hint: "Two opponents fight with gloves.",
  },
  { category: "Fruits", wordGuess: "MANGO", hint: "Sweet tropical fruit." },
  {
    category: "Movies",
    wordGuess: "JOKER",
    hint: "A villain with a painted smile.",
  },
  {
    category: "Food",
    wordGuess: "STEAK",
    hint: "Cooked meat usually eaten hot.",
  },
  { category: "Animals", wordGuess: "GIRAFFE", hint: "Tallest land animal." },
  { category: "Objects", wordGuess: "PEN", hint: "Used for writing." },
  {
    category: "Countries",
    wordGuess: "BRAZIL",
    hint: "Famous for football and carnival.",
  },
  { category: "Jobs", wordGuess: "CHEF", hint: "Prepares meals." },
  {
    category: "Sports",
    wordGuess: "VOLLEYBALL",
    hint: "Ball sport played over a net.",
  },
  {
    category: "Fruits",
    wordGuess: "GRAPES",
    hint: "Small fruit grown in clusters.",
  },
  {
    category: "Movies",
    wordGuess: "GLADIATOR",
    hint: "Historical warrior movie.",
  },
  { category: "Food", wordGuess: "SOUP", hint: "Liquid dish served warm." },
  {
    category: "Animals",
    wordGuess: "BEAR",
    hint: "Large animal that loves honey.",
  },
  { category: "Objects", wordGuess: "WATCH", hint: "Worn to tell time." },
  { category: "Countries", wordGuess: "SPAIN", hint: "Known for flamenco." },
  { category: "Jobs", wordGuess: "PILOT", hint: "Flies airplanes." },
  {
    category: "Sports",
    wordGuess: "GOLF",
    hint: "Played with clubs and small balls.",
  },
  {
    category: "Fruits",
    wordGuess: "STRAWBERRY",
    hint: "Red heart-shaped fruit.",
  },
  {
    category: "Movies",
    wordGuess: "INTERSTELLAR",
    hint: "Space and time-travel story.",
  },
  { category: "Food", wordGuess: "FRIES", hint: "Crispy potato sticks." },
  { category: "Animals", wordGuess: "WOLF", hint: "Lives in packs and howls." },
  {
    category: "Objects",
    wordGuess: "KEYBOARD",
    hint: "Used to type on a computer.",
  },
  {
    category: "Countries",
    wordGuess: "CANADA",
    hint: "Known for maple syrup.",
  },
  {
    category: "Jobs",
    wordGuess: "FARMER",
    hint: "Grows crops and raises animals.",
  },
  {
    category: "Sports",
    wordGuess: "CYCLING",
    hint: "Riding bicycles as sport.",
  },
  {
    category: "Fruits",
    wordGuess: "PINEAPPLE",
    hint: "Tropical fruit with spiky skin.",
  },
  {
    category: "Movies",
    wordGuess: "FROZEN",
    hint: "Animated movie with ice powers.",
  },
  {
    category: "Food",
    wordGuess: "SANDWICH",
    hint: "Food between slices of bread.",
  },
  { category: "Animals", wordGuess: "FOX", hint: "Clever red animal." },
  { category: "Objects", wordGuess: "MIRROR", hint: "Reflects images." },
  { category: "Countries", wordGuess: "CHINA", hint: "Has the Great Wall." },
  {
    category: "Jobs",
    wordGuess: "ARTIST",
    hint: "Creates paintings or drawings.",
  },
  {
    category: "Sports",
    wordGuess: "SKATING",
    hint: "Moving on wheels or ice.",
  },
  {
    category: "Fruits",
    wordGuess: "WATERMELON",
    hint: "Green outside, red inside.",
  },
  { category: "Movies", wordGuess: "UP", hint: "Adventure with flying house." },
  { category: "Food", wordGuess: "NOODLES", hint: "Long thin dough strands." },
  { category: "Animals", wordGuess: "DEER", hint: "Animal with antlers." },
  { category: "Objects", wordGuess: "BOTTLE", hint: "Holds liquids." },
  { category: "Countries", wordGuess: "MEXICO", hint: "Known for tacos." },
  { category: "Jobs", wordGuess: "BARBER", hint: "Cuts hair." },
  {
    category: "Sports",
    wordGuess: "TABLETENNIS",
    hint: "Fast racket sport on a table.",
  },
  {
    category: "Fruits",
    wordGuess: "PEACH",
    hint: "Soft fruit with fuzzy skin.",
  },
  { category: "Movies", wordGuess: "MOANA", hint: "Adventure on the ocean." },
  { category: "Food", wordGuess: "SALAD", hint: "Mixed vegetables dish." },
  { category: "Animals", wordGuess: "PANDA", hint: "Black and white bear." },
  { category: "Objects", wordGuess: "BOOK", hint: "Contains written pages." },
  { category: "Countries", wordGuess: "INDIA", hint: "Known for Bollywood." },
  { category: "Jobs", wordGuess: "DRIVER", hint: "Operates vehicles." },
  { category: "Sports", wordGuess: "RUGBY", hint: "Rough team sport." },
  { category: "Fruits", wordGuess: "CHERRY", hint: "Small red fruit." },
  { category: "Movies", wordGuess: "MATRIX", hint: "Virtual reality world." },
  { category: "Food", wordGuess: "CHEESE", hint: "Dairy product." },
  {
    category: "Animals",
    wordGuess: "CAMEL",
    hint: "Desert animal with humps.",
  },
  { category: "Objects", wordGuess: "SHOES", hint: "Worn on feet." },
  { category: "Countries", wordGuess: "RUSSIA", hint: "Largest country." },
  {
    category: "Jobs",
    wordGuess: "SCIENTIST",
    hint: "Studies the natural world.",
  },
  {
    category: "Sports",
    wordGuess: "ARCHERY",
    hint: "Shooting arrows at targets.",
  },
  { category: "Fruits", wordGuess: "PEAR", hint: "Sweet green fruit." },
  {
    category: "Movies",
    wordGuess: "TERMINATOR",
    hint: "Famous robot action movie.",
  },
  { category: "Food", wordGuess: "ICECREAM", hint: "Cold sweet dessert." },
  { category: "Animals", wordGuess: "DOLPHIN", hint: "Smart ocean animal." },
  {
    category: "Objects",
    wordGuess: "HEADPHONES",
    hint: "Used to listen to audio.",
  },
]
