export const word = [
  { category: "فواكه", wordGuess: "موز", hint: "ثمر أصفر يعطي طاقة" },
  { category: "طعام", wordGuess: "خبز", hint: "يؤكل مع وجبات و هو من القمح" },
  { category: "خضروات", wordGuess: "بصل", hint: "خضار يسبب دموع العين" },
  { category: "وظائف", wordGuess: "طبيب", hint: "يعالج المرضى" },
  { category: "رياضة", wordGuess: "قدم", hint: "لعبة جماعية مشهورة من 12 لاعب" },
  { category: "دول", wordGuess: "مصر", hint: "أم الدنيا" },
  { category: "حيوانات", wordGuess: "فيل", hint: "أكبر الحيوانات البرية" },
  { category: "فواكه", wordGuess: "عنب", hint: "ثمار صغيرة تنمو في عناقيد" },
  { category: "وظائف", wordGuess: "معلم", hint: "يشرح الدروس للطلاب" },
  { category: "رياضة", wordGuess: "سله", hint: "كرة تدخل في حلقة و تلعب بـ 5 لاعبين" },
  { category: "أدوات", wordGuess: "تلفاز", hint: "يعرض البرامج والمسلسلات" },
  { category: "دول", wordGuess: "الامارات", hint: "تحتوي على أطول برج" },
  { category: "حيوانات", wordGuess: "قرد", hint: "يحب أكل الموز بكثرة" },
  { category: "خضروات", wordGuess: "جزر", hint: "خضار برتقالي مفيد للنظر" },
  { category: "أدوات", wordGuess: "قلم", hint: "يستخدم للكتابة" },
  { category: "وظائف", wordGuess: "طباخ", hint: "يحضر الطعام والوجبات" },
  { category: "رياضة", wordGuess: "تنس", hint: "تُلعب بمضرب وكرة" },
  { category: "طعام", wordGuess: "أرز", hint: "حبوب بيضاء تستخدم في الأكل" },
  { category: "فواكه", wordGuess: "تين", hint: "ثمر لين وحلو الطعم" },
  { category: "دول", wordGuess: "يمن", hint: "دولة عربية جنوبية و تتميز بالمطبق" },
  { category: "حيوانات", wordGuess: "نمر", hint: "حيوان سريع وشرس" },
  { category: "أدوات", wordGuess: "هاتف", hint: "وسيلة للتواصل الصوتي" },
  { category: "وظائف", wordGuess: "سائق", hint: "يقود السيارة" },
  { category: "رياضة", wordGuess: "سباحه", hint: "رياضة مائية" },
  { category: "خضروات", wordGuess: "فجل", hint: "خضار له طعم لاذع" },
  { category: "طعام", wordGuess: "شوربه", hint: "طبق سائل ساخن" },
  { category: "حيوانات", wordGuess: "دب", hint: "حيوان ضخم وقوي" },
  { category: "أدوات", wordGuess: "ساعه", hint: "تُستخدم لمعرفة الوقت" },
  { category: "دول", wordGuess: "صين", hint: "ثاني اصعب لغة في العالم" },
  { category: "وظائف", wordGuess: "نجار", hint: "يعمل في تقطيع و انشاء الجماد بال" },
  { category: "رياضة", wordGuess: "ملاكمه", hint: "رياضة قتالية" },
  { category: "فواكه", wordGuess: "خوخ", hint: "ثمر ناعم ولذيذ" },
  { category: "حيوانات", wordGuess: "بطريق", hint: "طائر يعيش في الجليد" },
  { category: "أدوات", wordGuess: "مفتاح", hint: "يستخدم لفتح الأبواب" },
  { category: "دول", wordGuess: "سودان", hint: "دولة أفريقية كبيرة" },
  { category: "أدوات منزلية", wordGuess: "مكنسة", hint: "لتنظيف المنزل" },
  { category: "أدوات منزلية", wordGuess: "ثلاجة", hint: "لحفظ الطعام" },
  { category: "أدوات منزلية", wordGuess: "غسالة", hint: "لغسل الملابس" },
  { category: "أدوات منزلية", wordGuess: "فرن", hint: "لطهي الطعام" },
  { category: "أدوات منزلية", wordGuess: "مكواة", hint: "لكوي الملابس" },
  { category: "أدوات منزلية", wordGuess: "مروحة", hint: "لتبريد الهواء" },
  { category: "أدوات منزلية", wordGuess: "سخان", hint: "لتسخين المياه" },
  { category: "أدوات منزلية", wordGuess: "مقلاة", hint: "لقلي الطعام" },
  { category: "أدوات منزلية", wordGuess: "طنجرة", hint: "لطبخ الحساء" },
  { category: "أدوات منزلية", wordGuess: "مصباح", hint: "للإضاءة" },
  { category: "كرتون", wordGuess: "كونان", hint: "فتى محقق يحل الجرائم" },
  { category: "كرتون", wordGuess: "سالي", hint: "انا قصة انسان" },
  {
    category: "كرتون",
    wordGuess: "سندريلا",
    hint: "فتاة تتغير حياتها الى خادمة لاخواتها و مرت ابوها ",
  },
  {
    category: "كرتون",
    wordGuess: "ايروكا",
    hint: "فتاة تهوى الغناء و تواجهه صعوبات",
  },
  {
    category: "كرتون",
    wordGuess: "القناص",
    hint: "صائد محترف يبحث عن الأهداف",
  },
  { category: "كرتون", wordGuess: "جنى", hint: "فتاة شجاعة تدخل في مغامرات" },
  {
    category: "كرتون",
    wordGuess: "دورايمون",
    hint: "روبوت أزرق من المستقبل يساعد أصدقاءه",
  },
  {
    category: "كرتون",
    wordGuess: "بوكيمون",
    hint: "مخلوقات صغيرة يُجمعها المدربون",
  },
  {
    category: "كرتون",
    wordGuess: "تاما",
    hint: "قط مع اصدقائه يخوضون مغامرات",
  },
  {
    category: "كرتون",
    wordGuess: "ريمي",
    hint: "فتاة يتيمة تسافر وتعيش مغامرات",
  },
  { category: "كرتون", wordGuess: "سيمبا", hint: "أمير الغابة الأسد الشجاع" },
  {
    category: "كرتون",
    wordGuess: "ماوكلي",
    hint: "فتى تربى بين الحيوانات في الغابة",
  },
  {
    category: "كرتون",
    wordGuess: "الشبح",
    hint: "شاب يحب لعب كرة القدم و يسمى سابقا بالكابتن ماجد",
  },
]
